In [2]:
import pandas as pd
import matplotlib.pyplot as plt

!pip install openpyxl

Requirement already satisfied: openpyxl in /opt/anaconda3/envs/TIL6022/lib/python3.12/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /opt/anaconda3/envs/TIL6022/lib/python3.12/site-packages (from openpyxl) (1.1.0)

In [56]:
data_2014 = 'datasets_spitsuren_wegvakken/INWEVA_2014_spits.xlsx'
df2014 = pd.read_excel(data_2014)
df2014

,Baannr,Wegnr_van,Ri_van,Hec_letter_van,Hm_van,Baantype_van,Traject_van,Wegnr_naar,Ri_naar,Hec_letter_naar,...,OS_AL,OS_L1,OS_L2,OS_L3,OS_vrachtperc,AS_AL,AS_L1,AS_L2,AS_L3,AS_vrachtperc
0,237080,61,R,NaN,966,HR,MIDDENWG,61.0,R,NaN,...,524,429,56,39,18,737,623,66,48,15
1,237081,61,L,NaN,3665,HR,Middenweg,61.0,L,NaN,...,577,450,80,47,22,608,534,42,32,12
2,237082,61,R,NaN,3665,HR,Middenweg,61.0,R,NaN,...,590,494,56,40,16,755,641,66,48,15
3,237083,61,L,NaN,4771,HR,Middenweg,61.0,L,NaN,...,644,513,84,47,20,627,551,43,33,12
4,237084,61,R,NaN,4771,HR,Middenweg,61.0,R,NaN,...,590,494,56,40,16,755,641,66,48,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7855,6001811,16,L,n,71040,PKB,Hazeldonk,16.0,L,n,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
7856,6001812,16,L,n,71204,PST,Hazeldonk,16.0,L,n,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
7857,6001813,57,R,NaN,9297,HR,Dammenweg,57.0,R,NaN,...,686,626,38,22,9,1603,1534,45,24,4
7858,6001814,16,R,a,35926,AFR,DORDRECHT-CENTRUM 21A,16.0,R,a,...,795,788,2,5,1,1494,1491,1,2,0
7859,6001815,16,L,NaN,0,AFR,DORDRECHT-CENTRUM 21,NaN,L,NaN,...,148,141,2,5,5,201,198,1,2,1

In [66]:
df_road_4HR2014 = df2014[(df2014['Baantype_naar'] == 'HR') & (df2014['Baantype_van'] == 'HR')] 
df_road_4HR2014 = df2014[(df2014['Baantype_naar'] == 'HR') & (df2014['Baantype_van'] == 'HR') & df2014['Wegnr_naar'] == 4 ] 
df_road_4HR2014

,Baannr,Wegnr_van,Ri_van,Hec_letter_van,Hm_van,Baantype_van,Traject_van,Wegnr_naar,Ri_naar,Hec_letter_naar,...,OS_AL,OS_L1,OS_L2,OS_L3,OS_vrachtperc,AS_AL,AS_L1,AS_L2,AS_L3,AS_vrachtperc
0,237080,61,R,NaN,966,HR,MIDDENWG,61.0,R,NaN,...,524,429,56,39,18,737,623,66,48,15
1,237081,61,L,NaN,3665,HR,Middenweg,61.0,L,NaN,...,577,450,80,47,22,608,534,42,32,12
2,237082,61,R,NaN,3665,HR,Middenweg,61.0,R,NaN,...,590,494,56,40,16,755,641,66,48,15
3,237083,61,L,NaN,4771,HR,Middenweg,61.0,L,NaN,...,644,513,84,47,20,627,551,43,33,12
5,337001,61,R,NaN,6831,HR,Middenweg,61.0,R,NaN,...,720,619,58,43,14,820,703,70,47,14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7730,3000113,59,R,NaN,3332,HR,Nieuwe Koolweg,59.0,R,NaN,...,492,426,41,25,13,816,733,60,23,10
7733,5000069,59,L,NaN,36490,HR,Rijksweg,59.0,L,NaN,...,411,348,36,27,15,1065,1026,25,14,4
7738,6000019,61,R,NaN,21398,HR,Hoofdweg,61.0,R,NaN,...,1226,1032,111,83,16,1149,967,100,82,16
7762,6000264,4,NaN,NaN,228918,HR,RYKSWG,4.0,NaN,NaN,...,1397,1278,43,76,9,1462,1363,35,64,7
7763,6000266,4,NaN,NaN,228242,HR,RYKSWG,4.0,NaN,NaN,...,1585,1427,61,97,10,1470,1345,46,79,9

In [54]:
df_road_4HR_HM_R = df_road_4HR_HM[(df_road_4HR_HM['Ri_van'] == 'R') & (df_road_4HR_HM['Ri_naar'] == 'R') ]
mean_score_R_OS_AL = df_road_4HR_HM_R['OS_AL'].mean()
mean_score_R_AS_AL = df_road_4HR_HM_R['AS_AL'].mean()
print(f"mean_score_R_OS_AL: {mean_score_R_OS_AL}")
print(f"mean_score_R_AS_AL: {mean_score_R_AS_AL}")

df_road_4HR_HM_R

mean_score_R_OS_AL: 7842.490909090909
mean_score_R_AS_AL: 8778.454545454546

,VIAS-baannr,Wegnr_van,Ri_van,Hec_letter_van,Hm_van,Baantype_van,Traject_van,Wegnr_naar,Ri_naar,Hec_letter_naar,...,OS_L2,OS_L3,OS_vrachtperc,AS_AL,AS_L1,AS_L2,AS_L3,AS_vrachtperc,etmaal_AL_vorig_jaar,etmaal_AL_verschil
651,1730,4,R,NaN,54374.0,HR,Den Haag-Zuid,4,R,NaN,...,501,246,10,6820,6111,446,264,10,44270,4930
654,1733,4,R,NaN,52701.0,HR,Den Haag-Zuid,4,R,NaN,...,372,189,11,5251,4669,361,221,11,33126,3374
669,1784,4,R,NaN,55576.0,HR,Den Hoorn,4,R,NaN,...,434,272,11,5600,5080,336,185,9,38552,4148
670,1786,4,R,NaN,55149.0,HR,Den Hoorn,4,R,NaN,...,303,190,9,4947,4546,244,157,8,34667,3933
675,1793,4,R,NaN,51846.0,HR,Rijswijk,4,R,NaN,...,688,358,12,9945,8935,624,386,10,64386,4114
676,1794,4,R,NaN,50987.0,HR,Rijswijk,4,R,NaN,...,657,373,13,9065,8180,510,376,10,58389,2811
685,1834,4,R,NaN,50246.0,HR,Kntr Plaspoelpolder,4,R,NaN,...,624,439,10,12012,11115,454,444,7,78959,2641
695,1873,4,R,NaN,49718.0,HR,Kp Ypenburg,4,R,NaN,...,621,370,10,10227,9270,523,435,9,68472,2328
736,1955,4,R,NaN,48793.0,HR,Kp Ypenburg,4,R,NaN,...,605,367,12,8713,7787,503,424,11,59851,2049
740,1960,4,R,NaN,48340.0,HR,Rijswijk-Centrum,4,R,NaN,...,621,373,9,10320,9376,527,418,9,68683,2317
789,2049,4,R,NaN,71310.0,HR,A4,4,R,NaN,...,0,0,0,6584,6584,0,0,0,40109,4391
794,2054,4,R,NaN,70594.0,HR,Kp Kethelplein,4,R,NaN,...,538,503,8,12520,11805,354,362,6,76500,7300
811,2074,4,R,NaN,47597.0,HR,Kp Prins Clausplein,4,R,NaN,...,665,383,9,11088,10112,553,423,9,75020,2180
815,2078,4,R,NaN,46743.0,HR,Kp Ypenburg,4,R,NaN,...,444,257,13,5070,4429,359,283,13,36520,280
856,2140,4,R,NaN,72021.0,HR,A4,4,R,NaN,...,0,0,0,6629,6629,0,0,0,40109,4491
872,2166,4,R,NaN,45745.0,HR,Leidschendam,4,R,NaN,...,751,401,12,9631,8597,620,414,11,67721,1479
900,2197,4,R,NaN,75252.0,HR,Kp Benelux,4,R,NaN,...,239,257,7,7938,7533,184,222,5,43009,4791
903,2200,4,R,NaN,74575.0,HR,Beneluxweg,4,R,NaN,...,479,474,7,14264,13586,324,355,5,80667,7633
905,2202,4,R,NaN,74135.0,HR,Beneluxweg,4,R,NaN,...,0,0,0,6629,6629,0,0,0,40109,4491
937,2265,4,R,NaN,97825.0,HR,Kp Hellegatsplein,4,R,NaN,...,204,392,20,4464,3923,189,352,12,21375,1025
963,2302,4,R,NaN,99468.0,HR,N59,4,R,NaN,...,264,451,20,5137,4429,299,409,14,25358,1042
964,2303,4,R,NaN,94939.0,HR,Buttervliet,4,R,NaN,...,304,471,20,6396,5686,298,412,11,29696,1304
966,2305,4,R,NaN,76904.0,HR,A4,4,R,NaN,...,116,178,8,3427,3154,91,182,8,20320,1680
1020,2404,4,R,NaN,103173.0,HR,Kp Sabina,4,R,NaN,...,163,327,23,3081,2633,141,308,15,15390,1410
1022,2414,4,R,NaN,101255.0,HR,Willemstad,4,R,NaN,...,235,432,20,4772,4111,264,398,14,23582,1018
1027,2419,4,R,NaN,94179.0,HR,Buttervliet,4,R,NaN,...,304,471,20,6396,5686,298,412,11,29696,1304
1028,2423,4,R,NaN,93330.0,HR,Numansdorp,4,R,NaN,...,297,467,20,6266,5567,288,411,11,29696,904
1030,2426,4,R,NaN,92250.0,HR,Numansdorp,4,R,NaN,...,205,421,21,5503,4947,182,375,10,26073,827
1040,2441,4,R,NaN,43402.0,HR,Leidschendam,4,R,NaN,...,692,375,16,6972,6012,567,394,14,49219,981
1054,2461,4,R,NaN,101605.0,HR,Willemstad,4,R,NaN,...,234,456,19,5162,4489,258,416,13,24957,1843
1263,2867,4,R,NaN,36129.0,HR,A4,4,R,NaN,...,831,438,12,10342,9258,650,434,10,74255,845
1379,3054,4,R,NaN,32870.0,HR,A4,4,R,NaN,...,482,303,11,6789,6073,394,322,11,53969,531
1395,3074,4,R,NaN,30407.0,HR,Hoogmade,4,R,NaN,...,566,353,10,9535,8647,488,401,9,67553,747
1531,3309,4,R,NaN,28268.0,HR,Hoogmade,4,R,NaN,...,529,345,12,8009,7150,463,397,11,59317,583
1557,3340,4,R,NaN,23859.0,HR,Roelofarendsveen,4,R,NaN,...,566,380,12,8938,7997,507,435,11,64303,697
1640,3489,4,R,NaN,22845.0,HR,Roelofarendsveen,4,R,NaN,...,473,323,10,8340,7524,434,382,10,61133,67
1711,3637,4,R,NaN,19400.0,HR,Nieuw-Vennep,4,R,NaN,...,483,331,10,9333,8477,462,395,9,64604,1696
1775,3746,4,R,NaN,18186.0,HR,A44,4,R,NaN,...,394,245,9,8074,7435,354,286,8,59240,-240
1795,3779,4,R,NaN,16674.0,HR,Nieuw-Vennep,4,R,NaN,...,537,299,8,13385,12565,484,336,6,86168,1332
1851,3901,4,R,NaN,15326.0,HR,Den Ruygen Hoek,4,R,NaN,...,567,321,7,16423,15524,536,364,5,101693,3207
1894,3978,4,R,NaN,14560.0,HR,Den Ruygen Hoek,4,R,NaN,...,536,303,7,15182,14349,496,337,5,101693,-4493
1918,4024,4,R,NaN,13678.0,HR,A4,4,R,NaN,...,565,320,7,16456,15554,538,365,5,101693,2807
1974,4150,4,R,NaN,10796.0,HR,A5,4,R,NaN,...,507,279,8,12279,11582,404,294,6,82228,1172
2100,4366,4,R,NaN,9865.0,HR,A4,4,R,NaN,...,470,157,10,8563,8023,378,163,6,56266,234
2205,4592,4,R,NaN,9072.0,HR,Schiphol,4,R,NaN,...,546,201,7,13410,12768,451,191,5,79890,2010
2247,4667,4,R,NaN,7827.0,HR,A4,4,R,NaN,...,433,104,6,10835,10217,437,182,6,64008,1092
2278,4728,4,R,NaN,6094.0,HR,Schiphol,4,R,NaN,...,431,103,6,10772,10159,434,180,6,67506,-3106
2315,4821,4,R,NaN,3390.0,HR,Kp Badhoevedorp,4,R,NaN,...,370,79,7,8421,7861,394,166,7,65934,-14234
2363,4947,4,R,NaN,2752.0,HR,Amsterdam-Sloten,4,R,NaN,...,577,170,6,14792,13828,682,282,7,98064,-2264
2416,5041,4,R,NaN,1851.0,HR,Amsterdam-Sloten,4,R,NaN,...,565,160,6,12848,12073,581,195,6,89753,-3153
2433,5087,4,R,NaN,1419.0,HR,Kp De Nieuwe Meer,4,R,NaN,...,641,183,6,14787,13972,610,205,6,97019,3481
2450,5111,4,R,NaN,21.0,HR,Ringweg-Zuid,4,R,NaN,...,347,130,6,9985,9447,374,165,5,64680,220
8215,17432,4,R,NaN,56799.0,HR,Delft,4,R,NaN,...,324,259,10,4635,4208,254,173,9,31417,4783
8221,17438,4,R,NaN,57361.0,HR,Delft,4,R,NaN,...,351,267,10,5632,5157,292,184,8,35080,5520
8223,17440,4,R,NaN,61050.0,HR,Kp Kethelplein,4,R,NaN,...,224,226,9,4221,3837,218,166,9,25401,4499

In [40]:
df_road_4HR_HM_L = df_road_4HR_HM[(df_road_4HR_HM['Ri_van'] == 'L') & (df_road_4HR_HM['Ri_naar'] == 'L') ]
display(df_road_4HR_HM_L)

,VIAS-baannr,Wegnr_van,Ri_van,Hec_letter_van,Hm_van,Baantype_van,Traject_van,Wegnr_naar,Ri_naar,Hec_letter_naar,...,OS_L2,OS_L3,OS_vrachtperc,AS_AL,AS_L1,AS_L2,AS_L3,AS_vrachtperc,etmaal_AL_vorig_jaar,etmaal_AL_verschil
598,1731,4.0,L,NaN,55087,HR,Den Hoorn,4.0,L,NaN,...,815,425,17,7923,6830,733,361,14,53247,953
599,1732,4.0,L,NaN,54369,HR,Den Haag-Zuid,4.0,L,NaN,...,716,335,18,5632,4694,655,284,17,39939,861
601,1750,4.0,L,NaN,52642,HR,Den Haag-Zuid,4.0,L,NaN,...,1109,543,16,9991,8615,889,487,14,71117,2083
609,1787,4.0,L,NaN,55578,HR,Den Hoorn,4.0,L,NaN,...,530,360,15,6469,5720,459,290,12,43005,1795
615,1795,4.0,L,NaN,51914,HR,Rijswijk,4.0,L,NaN,...,686,448,12,8462,7641,455,366,10,62649,1851
621,1827,4.0,L,NaN,56767,HR,Delft,4.0,L,NaN,...,578,376,14,7590,6743,537,310,11,48281,1819
624,1835,4.0,L,NaN,50996,HR,Rijswijk,4.0,L,NaN,...,826,469,10,10961,10029,555,378,9,82763,2637
632,1874,4.0,L,NaN,50162,HR,Kntr Plaspoelpolder,4.0,L,NaN,...,484,390,11,7047,6421,284,343,9,56492,1908
696,2015,4.0,L,NaN,48408,HR,Kp Ypenburg,4.0,L,NaN,...,565,431,8,11706,11033,311,363,6,80544,2856
722,2055,4.0,L,NaN,71216,HR,A4,4.0,L,NaN,...,714,742,11,14033,12718,583,733,9,86431,3069
724,2057,4.0,L,NaN,70559,HR,Kp Kethelplein,4.0,L,NaN,...,424,348,15,5733,5040,397,297,12,35081,1819
743,2080,4.0,L,NaN,47495,HR,Kp Prins Clausplein,4.0,L,NaN,...,140,276,8,5600,5313,54,233,5,38375,2025
788,2167,4.0,L,NaN,46485,HR,Rotterdamseweg,4.0,L,NaN,...,553,415,11,10274,9530,408,337,7,69414,486
816,2198,4.0,L,NaN,75538,HR,Kp Benelux,4.0,L,NaN,...,489,603,8,14483,13522,372,589,7,89852,2948
831,2222,4.0,L,NaN,45648,HR,Leidschendam,4.0,L,NaN,...,289,328,10,7221,6671,254,297,8,47790,3310
851,2267,4.0,L,NaN,97845,HR,Kp Hellegatsplein,4.0,L,NaN,...,262,446,13,4933,4182,275,477,15,31760,240
871,2300,4.0,L,NaN,99723,HR,Kp Hellegatsplein,4.0,L,NaN,...,163,395,15,3995,3356,200,440,16,23223,977
919,2413,4.0,L,NaN,102047,HR,Willemstad,4.0,L,NaN,...,252,462,18,4468,3755,255,459,16,26108,492
924,2418,4.0,L,NaN,101250,HR,Willemstad,4.0,L,NaN,...,274,450,17,4723,4005,265,454,15,27160,940
925,2425,4.0,L,NaN,93396,HR,Numansdorp,4.0,L,NaN,...,224,428,13,4256,3541,243,473,17,28194,906
931,2439,4.0,L,NaN,43270,HR,Leidschendam,4.0,L,NaN,...,297,350,7,12011,11475,232,304,4,74956,4944
942,2458,4.0,L,NaN,103204,HR,Kp Sabina,4.0,L,NaN,...,259,469,17,4813,4113,242,458,15,27724,976
1126,2868,4.0,L,NaN,35704,HR,A4,4.0,L,NaN,...,247,260,8,7449,6966,210,274,6,55218,-518
1205,3005,4.0,L,NaN,32504,HR,A4,4.0,L,NaN,...,382,338,7,10526,9898,304,325,6,72181,819
1339,3247,4.0,L,NaN,30220,HR,Hoogmade,4.0,L,NaN,...,355,330,8,8846,8239,291,316,7,63208,992
1390,3341,4.0,L,NaN,28680,HR,Hoogmade,4.0,L,NaN,...,426,390,8,9438,8761,330,347,7,68228,1072
1469,3541,4.0,L,NaN,23901,HR,Roelofarendsveen,4.0,L,NaN,...,381,373,8,8962,8338,292,333,7,66228,672
1473,3558,4.0,L,NaN,22843,HR,Roelofarendsveen,4.0,L,NaN,...,483,407,8,9439,8755,346,339,7,70356,1144
1570,3745,4.0,L,NaN,19234,HR,Nieuw-Vennep,4.0,L,NaN,...,420,352,8,8097,7510,290,298,7,64109,991
1587,3778,4.0,L,NaN,17749,HR,A44,4.0,L,NaN,...,637,481,7,11552,10756,428,368,7,92255,645
1736,4151,4.0,L,NaN,13749,HR,A4,4.0,L,NaN,...,573,439,6,11227,10608,354,266,6,89876,124
1855,4375,4.0,L,NaN,10823,HR,Kp De Hoek,4.0,L,NaN,...,347,175,5,7074,6785,210,80,4,58689,1911
1903,4511,4.0,L,NaN,10022,HR,A4,4.0,L,NaN,...,461,206,5,10499,10071,312,117,4,82679,321
1933,4594,4.0,L,NaN,9255,HR,Schiphol,4.0,L,NaN,...,420,186,5,9180,8778,296,107,4,67570,-370
2010,4770,4.0,L,NaN,6128,HR,Schiphol,4.0,L,NaN,...,502,223,5,12174,11707,342,126,4,93802,-2
2037,4822,4.0,L,NaN,5150,HR,Kp Badhoevedorp,4.0,L,NaN,...,394,122,5,8547,8160,290,98,5,67844,-1744
2064,4908,4.0,L,NaN,3274,HR,Kp Badhoevedorp,4.0,L,NaN,...,651,200,5,13485,12890,429,166,4,102260,440
2127,5040,4.0,L,NaN,2550,HR,Amsterdam-Sloten,4.0,L,NaN,...,604,167,6,11481,10912,413,156,5,88866,234
2141,5086,4.0,L,NaN,1805,HR,Amsterdam-Sloten,4.0,L,NaN,...,644,197,6,13252,12634,455,164,5,98412,1088
2166,5137,4.0,L,NaN,952,HR,Kp De Nieuwe Meer,4.0,L,NaN,...,517,177,6,8768,8319,315,135,5,66766,1434
6763,17433,4.0,L,NaN,57480,HR,Delft,4.0,L,NaN,...,507,362,15,6174,5422,457,296,12,40925,2175
6765,17435,4.0,L,NaN,62866,HR,Kp Kethelplein,4.0,L,NaN,...,495,391,13,7405,6647,433,326,10,47114,2486
6766,17436,4.0,L,NaN,70111,HR,Kp Kethelplein,4.0,L,NaN,...,495,373,14,6412,5649,449,315,12,40431,1969
6880,22325,4.0,L,NaN,3997,HR,Kp Badhoevedorp,4.0,L,NaN,...,524,165,5,10774,10261,366,148,5,-9223370000000000000,-9223370000000000000
7452,2051,4.0,L,NaN,72261,HR,A4,4.0,L,NaN,...,275,307,8,7175,6742,188,245,6,45446,1654
7462,2139,4.0,L,NaN,73960,HR,Beneluxweg,4.0,L,NaN,...,275,307,8,7175,6742,188,245,6,45446,1654
7464,2201,4.0,L,NaN,74312,HR,Beneluxweg,4.0,L,NaN,...,275,307,8,7175,6742,188,245,6,45446,1654
7594,3900,4.0,L,NaN,17209,HR,Nieuw-Vennep,4.0,L,NaN,...,750,567,7,13714,12803,492,420,7,110540,1760
7607,3977,4.0,L,NaN,15351,HR,Den Ruygen Hoek,4.0,L,NaN,...,750,567,7,13714,12803,492,420,7,110540,1760
7614,4025,4.0,L,NaN,14637,HR,Den Ruygen Hoek,4.0,L,NaN,...,750,567,7,13714,12803,492,420,7,110540,1760

In [6]:
data_2015 = 'datasets_spitsuren_wegvakken/definitief_INWEVA_2015_spits.xlsx'
df2015 = pd.read_excel(data_2015)
df2015

,Baannr,Wegnr_van,Ri_van,Hec_letter_van,Hm_van,Baantype_van,Traject_van,Wegnr_naar,Ri_naar,Hec_letter_naar,...,OS_AL,OS_L1,OS_L2,OS_L3,OS_vrachtperc,AS_AL,AS_L1,AS_L2,AS_L3,AS_vrachtperc
0,338011,58,R,NaN,166038,HR,RYKSWG,58,R,NaN,...,2129,1931,145,53,9,2510,2405,83,22,4
1,338012,58,R,a,167134,PST,MIDDELBURG 39,58,R,a,...,1324,1171,97,56,12,1313,1239,51,23,6
2,338013,58,R,NaN,166764,HR,RYKSWG,58,R,NaN,...,3279,2959,221,99,10,3636,3464,127,45,5
3,338014,58,R,b,167291,OPR,MIDDELBURG 39,58,R,b,...,647,600,35,12,7,1045,995,43,7,5
4,338015,58,R,NaN,167134,HR,RYKSWG,58,R,NaN,...,1842,1670,132,40,9,2205,2103,83,19,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7755,6002555,N421,R,NaN,2737,HR,HOUTEN-OOST 18A,N421,R,NaN,...,530,485,34,11,8,159,144,13,2,9
7756,6002556,15,R,NaN,51667,HR,RYKSWG,15,R,NaN,...,6589,5851,241,497,11,8087,7714,140,233,5
7757,6002557,15,R,NaN,53950,HR,RYKSWG,15,R,NaN,...,6864,6063,279,522,12,9057,8558,190,309,6
7758,6002558,15,R,b,53845,OPR,HEIJPLAAT 18,15,R,NaN,...,472,217,95,160,54,695,469,79,147,33
7759,6002559,73,R,x,46750,VBR,GRUBBENVORST 12,73,R,x,...,2959,2456,234,269,17,2742,2288,170,284,17

In [7]:
df_road_4HR_2015 = df2015[(df2015['Wegnr_van'] == 4) & (df2015["Wegnr_naar"] == 4) & (df2015['Baantype_naar'] == 'HR') & (df2015['Baantype_van'] == 'HR')] 
df_road_4HR_HM_2015 = df_road_4HR_2015[(df_road_4HR_2015['Hm_van'] <= 150000) & (df_road_4HR_2015['Hm_naar'] <= 150000)]
df_road_4HR_HM_2015

,Baannr,Wegnr_van,Ri_van,Hec_letter_van,Hm_van,Baantype_van,Traject_van,Wegnr_naar,Ri_naar,Hec_letter_naar,...,OS_AL,OS_L1,OS_L2,OS_L3,OS_vrachtperc,AS_AL,AS_L1,AS_L2,AS_L3,AS_vrachtperc
533,840028,4,L,NaN,103204,HR,RYKSWG,4,L,NaN,...,4123,3563,222,338,14,3687,3102,198,387,16
534,840029,4,R,NaN,103173,HR,RYKSWG,4,R,NaN,...,1557,1190,108,259,24,2756,2390,119,247,13
546,841004,4,R,NaN,92250,HR,RYKSWG,4,R,NaN,...,2442,1887,191,364,23,5711,5132,238,341,10
548,841006,4,L,NaN,93396,HR,RYKSWG,4,L,NaN,...,4973,4476,187,310,10,3267,2675,190,402,18
549,841007,4,R,NaN,93330,HR,RYKSWG,4,R,NaN,...,3097,2458,239,400,21,6404,5749,288,367,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2117,1148087,4,L,NaN,6128,HR,Rijksweg A4,4,L,NaN,...,14449,13782,353,314,5,11907,11446,269,192,4
2119,1148089,4,R,NaN,6269,HR,Rijksweg A4,4,R,NaN,...,9050,8589,332,129,5,12031,11378,439,214,5
2120,1148090,4,R,NaN,9072,HR,Rijksweg A4,4,R,NaN,...,9920,9284,432,204,6,14258,13540,480,238,5
2174,1148147,4,L,NaN,952,HR,Nieuwe Haagseweg,4,L,NaN,...,10623,10216,202,205,4,8168,7855,160,153,4
2176,1148149,4,R,NaN,21,HR,Nieuwe Haagseweg,4,R,NaN,...,8455,7978,305,172,6,10696,10302,269,125,4

In [9]:
df_road_4HR_HM_R_2015 = df_road_4HR_HM_2015[(df_road_4HR_HM_2015['Ri_van'] == 'R') & (df_road_4HR_HM_2015['Ri_naar'] == 'R') ]
mean_score_R_OS_AL2015 = df_road_4HR_HM_R_2015['OS_AL'].mean()
mean_score_R_AS_AL2015 = df_road_4HR_HM_R_2015['AS_AL'].mean()
print(f"mean_score_R_OS_AL2015: {mean_score_R_OS_AL2015}")
print(f"mean_score_R_AS_AL2015: {mean_score_R_AS_AL2015}")

df_road_4HR_HM_R_2015

mean_score_R_OS_AL2015: 7126.833333333333
mean_score_R_AS_AL2015: 9209.770833333334

,Baannr,Wegnr_van,Ri_van,Hec_letter_van,Hm_van,Baantype_van,Traject_van,Wegnr_naar,Ri_naar,Hec_letter_naar,...,OS_AL,OS_L1,OS_L2,OS_L3,OS_vrachtperc,AS_AL,AS_L1,AS_L2,AS_L3,AS_vrachtperc
534,840029,4,R,NaN,103173,HR,RYKSWG,4,R,NaN,...,1557,1190,108,259,24,2756,2390,119,247,13
546,841004,4,R,NaN,92250,HR,RYKSWG,4,R,NaN,...,2442,1887,191,364,23,5711,5132,238,341,10
549,841007,4,R,NaN,93330,HR,RYKSWG,4,R,NaN,...,3097,2458,239,400,21,6404,5749,288,367,10
557,841015,4,R,NaN,101255,HR,RYKSWG,4,R,NaN,...,2713,2166,181,366,20,4665,4067,246,352,13
560,841018,4,R,NaN,101605,HR,RYKSWG,4,R,NaN,...,2887,2325,181,381,19,4911,4308,240,363,12
563,841021,4,R,NaN,97825,HR,RYKSWG,4,R,NaN,...,2336,1849,157,330,21,4398,3906,182,310,11
564,841022,4,R,NaN,99468,HR,RYKSWG,4,R,NaN,...,2918,2340,197,381,20,4992,4365,271,356,13
596,843055,4,R,NaN,71310,HR,RYKSWG,4,R,NaN,...,5114,5114,0,0,0,5429,5429,0,0,0
597,843056,4,R,NaN,75292,HR,BENELUXWG,4,R,NaN,...,5359,4901,203,255,9,6499,6086,171,242,6
656,843123,4,R,NaN,70575,HR,RYKSWG,4,R,NaN,...,9983,9035,516,432,9,10667,10056,295,316,6
673,843148,4,R,NaN,72020,HR,RYKSWG,4,R,NaN,...,5114,5114,0,0,0,5429,5429,0,0,0
674,843149,4,R,NaN,74135,HR,Beneluxweg,4,R,NaN,...,5096,5096,0,0,0,5403,5403,0,0,0
675,843150,4,R,NaN,74575,HR,Beneluxweg,4,R,NaN,...,9924,8971,469,484,10,11897,11190,323,384,6
703,843189,4,R,NaN,76894,HR,BENELUXWG,4,R,NaN,...,2589,1975,290,324,24,2912,2285,267,360,22
751,844042,4,R,NaN,55148,HR,RYKSWG,4,R,NaN,...,1200,1118,72,10,7,1913,1859,48,6,3
757,844052,4,R,NaN,52701,HR,RYKSWG,4,R,NaN,...,1717,1551,120,46,10,3507,3218,193,96,8
758,844053,4,R,NaN,54373,HR,RYKSWG,4,R,NaN,...,2713,2450,203,60,10,4612,4252,254,106,8
768,844064,4,R,NaN,50987,HR,RYKSWG,4,R,NaN,...,5304,4694,422,188,12,8628,7959,428,241,8
770,844066,4,R,NaN,51846,HR,RYKSWG,4,R,NaN,...,5710,5062,447,201,11,9208,8481,476,251,8
795,845035,4,R,NaN,45745,HR,RYKSWG,4,R,NaN,...,9030,7946,683,401,12,9378,8353,631,394,11
797,845038,4,R,NaN,47597,HR,RYKSWG,4,R,NaN,...,9776,8340,919,517,15,11589,10200,846,543,12
798,845039,4,R,NaN,48340,HR,RYKSWG,4,R,NaN,...,8579,7907,463,209,8,10594,9881,451,262,7
802,845047,4,R,NaN,50246,HR,RYKSWG,4,R,NaN,...,8193,7449,513,231,9,12407,11712,422,273,6
845,845114,4,R,NaN,46743,HR,RYKSWG,4,R,NaN,...,4174,3224,599,351,23,5146,4136,621,389,20
857,845129,4,R,NaN,48793,HR,RYKSWG,4,R,NaN,...,6172,5542,436,194,10,9187,8513,417,257,7
864,845139,4,R,NaN,49754,HR,RYKSWG,4,R,NaN,...,7251,6565,480,206,9,10834,10120,449,265,7
873,845152,4,R,NaN,43402,HR,RYKSWG,4,R,NaN,...,6282,5274,631,377,16,6841,5912,562,367,14
1250,946007,4,R,NaN,28268,HR,RYKSWG,4,R,NaN,...,7785,6924,533,328,11,9185,8248,569,368,10
1252,946009,4,R,NaN,30407,HR,Rijksweg A4,4,R,NaN,...,9158,8248,563,347,10,10399,9409,602,388,10
1258,946020,4,R,NaN,36129,HR,RYKSWG,4,R,NaN,...,10725,9462,792,471,12,10682,9582,663,437,10
1320,946126,4,R,NaN,32870,HR,RYKSWG,4,R,NaN,...,7356,6595,462,299,10,7268,6512,452,304,10
1662,1046004,4,R,NaN,22845,HR,RYKSWG,4,R,NaN,...,8011,7208,496,307,10,9700,8837,517,346,9
1663,1046007,4,R,NaN,23859,HR,RYKSWG,4,R,NaN,...,8496,7562,571,363,11,10115,9087,619,409,10
1672,1047005,4,R,NaN,10796,HR,Rijksweg A4,4,R,NaN,...,10380,9648,505,227,7,14569,13795,513,261,5
1675,1047008,4,R,NaN,13678,HR,Rijksweg A4,4,R,NaN,...,12444,11576,584,284,7,18572,17622,615,335,5
1686,1047019,4,R,NaN,16674,HR,RYKSWG,4,R,NaN,...,10795,9994,538,263,7,15192,14334,551,307,6
1687,1047020,4,R,NaN,18186,HR,RYKSWG,4,R,NaN,...,7369,6753,408,208,8,9732,9045,427,260,7
1696,1047029,4,R,NaN,19400,HR,RYKSWG,4,R,NaN,...,8491,7661,510,320,10,10669,9761,540,368,9
1703,1047036,4,R,NaN,9865,HR,Rijksweg A4,4,R,NaN,...,6647,6106,368,173,8,10450,9810,422,218,6
2036,1147019,4,R,NaN,7827,HR,Rijksweg A4,4,R,NaN,...,8712,8268,319,125,5,11752,11114,430,208,5
2101,1148069,4,R,NaN,1419,HR,Nieuwe Haagseweg,4,R,NaN,...,13427,12682,498,247,6,15580,14973,417,190,4
2104,1148072,4,R,NaN,1851,HR,Nieuwe Haagseweg,4,R,NaN,...,12537,11822,472,243,6,14309,13727,399,183,4
2110,1148080,4,R,NaN,2752,HR,Nieuwe Haagseweg,4,R,NaN,...,13512,12779,481,252,5,16302,15539,493,270,5
2111,1148081,4,R,NaN,3397,HR,Rijksweg A4,4,R,NaN,...,9197,8807,277,113,4,10696,10119,382,195,5
2115,1148085,4,R,NaN,5003,HR,Rijksweg A4,4,R,NaN,...,12391,11834,401,156,4,13995,13310,461,224,5
2119,1148089,4,R,NaN,6269,HR,Rijksweg A4,4,R,NaN,...,9050,8589,332,129,5,12031,11378,439,214,5
2120,1148090,4,R,NaN,9072,HR,Rijksweg A4,4,R,NaN,...,9920,9284,432,204,6,14258,13540,480,238,5
2176,1148149,4,R,NaN,21,HR,Nieuwe Haagseweg,4,R,NaN,...,8455,7978,305,172,6,10696,10302,269,125,4

In [60]:
import pandas as pd

# List of file paths for the datasets for each year (2012 to 2019)
data_files = {
    2012: 'datasets_spitsuren_wegvakken/INWEVA_2012_spits.xlsx',
    2013: 'datasets_spitsuren_wegvakken/INWEVA_2013_spits.xlsx',
    2014: 'datasets_spitsuren_wegvakken/INWEVA_2014_spits.xlsx',
    2015: 'datasets_spitsuren_wegvakken/INWEVA_2015_spits.xlsx',
    2016: 'datasets_spitsuren_wegvakken/INWEVA_2016_spits.xlsx',
    2017: 'datasets_spitsuren_wegvakken/INWEVA_2017_spits.xlsx',
    2018: 'datasets_spitsuren_wegvakken/INWEVA_2018_spits.xlsx',
    2019: 'datasets_spitsuren_wegvakken/INWEVA_2019_spits.xlsx'
}

# Initialize an empty list to store results
results = []

# Loop through the datasets
for year, file in data_files.items():
    # Load the dataset for the year
    df = pd.read_excel(file)
    
    # Filter the data for road 4 with HR (Hoofdroute)
    df_road_4HR = df[(df['Wegnr_van'] == 4) & (df["Wegnr_naar"] == 4) & (df['Baantype_naar'] == 'HR') & (df['Baantype_van'] == 'HR')]
    
    # Further filter for Hectometer <= 150,000
    df_road_4HR_HM = df_road_4HR[(df_road_4HR['Hm_van'] <= 150000) & (df_road_4HR['Hm_naar'] <= 150000)]
    
    # Separate data for 'R' (right) direction
    df_road_4HR_HM_R = df_road_4HR_HM[(df_road_4HR_HM['Ri_van'] == 'R') & (df_road_4HR_HM['Ri_naar'] == 'R')]
    df_road_4HR_HM_L = df_road_4HR_HM[(df_road_4HR_HM['Ri_van'] == 'L') & (df_road_4HR_HM['Ri_naar'] == 'L')]
    
    # Calculate the mean score for OS_AL (morning rush) and AS_AL (afternoon rush)
    mean_score_R_OS_R = df_road_4HR_HM_R['OS_AL'].mean()
    mean_score_R_AS_R = df_road_4HR_HM_R['AS_AL'].mean()

    mean_score_R_OS_L = df_road_4HR_HM_L['OS_AL'].mean()
    mean_score_R_AS_L = df_road_4HR_HM_L['AS_AL'].mean()
    
     # Store the results for the right side
    results.append({
        'Year': year,
        'Rush': 'Morning',  # OS represents morning rush hour
        'Direction': 'R',   # Right-hand side
        'Mean Score': mean_score_R_OS_R
    })
    
    results.append({
        'Year': year,
        'Rush': 'Afternoon',  # AS represents afternoon rush hour
        'Direction': 'R',      # Right-hand side
        'Mean Score': mean_score_R_AS_R
    })
    
    # Store the results for the left side
    results.append({
        'Year': year,
        'Rush': 'Morning',  # OS represents morning rush hour
        'Direction': 'L',   # Left-hand side
        'Mean Score': mean_score_R_OS_L
    })
    
    results.append({
        'Year': year,
        'Rush': 'Afternoon',  # AS represents afternoon rush hour
        'Direction': 'L',      # Left-hand side
        'Mean Score': mean_score_R_AS_L
    })

# Convert the results into a DataFrame
df_results = pd.DataFrame(results)

# Export the results to an Excel file
df_results.to_excel('mean_scores_road4_HR_R_2012_2019.xlsx', index=False)

display(df_results)

/opt/anaconda3/envs/TIL6022/lib/python3.12/site-packages/openpyxl/worksheet/header_footer.py:48: UserWarning: Cannot parse header or footer so it will be ignored
  warn("""Cannot parse header or footer so it will be ignored""")

    Year       Rush Direction   Mean Score
0   2012    Morning         R  4865.486111
1   2012  Afternoon         R  6232.222222
2   2012    Morning         L  5928.235294
3   2012  Afternoon         L  4930.235294
4   2013    Morning         R          NaN
5   2013  Afternoon         R          NaN
6   2013    Morning         L          NaN
7   2013  Afternoon         L          NaN
8   2014    Morning         R          NaN
9   2014  Afternoon         R          NaN
10  2014    Morning         L          NaN
11  2014  Afternoon         L          NaN
12  2015    Morning         R  7126.833333
13  2015  Afternoon         R  9209.770833
14  2015    Morning         L  9070.404762
15  2015  Afternoon         L  7610.547619
16  2016    Morning         R  7842.240000
17  2016  Afternoon         R  9079.440000
18  2016    Morning         L  9234.543478
19  2016  Afternoon         L  8471.913043
20  2017    Morning         R  7842.490909
21  2017  Afternoon         R  8778.454545
22  2017    Morning         L  9693.760000
23  2017  Afternoon         L  8742.480000
24  2018    Morning         R  7835.000000
25  2018  Afternoon         R  8589.740741
26  2018    Morning         L  9796.000000
27  2018  Afternoon         L  8774.640000
28  2019    Morning         R  7931.611111
29  2019  Afternoon         R  8605.462963
30  2019    Morning         L  9875.680000
31  2019  Afternoon         L  8915.040000